### ISSUE TITLE
using celery_sqlalchemy_scheduler in flask app 

### ISSUE THREAD

**Issue by saadqc** [tuomur/celery_sqlalchemy_scheduler#1]
After searching alot, i finally found this. But i dont know how to run this.
See, i added the schedule and schedule model in my flask project and set the CELERYBEAT_SCHEDULER = 'scheduler.sqlalchemy_scheduler:DatabaseScheduler'
 to my project and your file name. The app is running and so is the beat. now how to add periodic task dynamically ? any code snippet ?

Tables are created in db too

Celery beat working with the sqlalchemy
Configuration ->
    . broker -> redis://localhost:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> app.sqlalchemy_scheduler.DatabaseScheduler

```
. logfile -> [stderr]@%INFO
. maxinterval -> now (0s)
```

[2015-11-13 16:40:37,838: INFO/MainProcess] beat: Starting...

**Comment by tuomur** [comment]
My primary use case was a REST API to manipulate the `model.DatabaseSchedulerEntry` objects. Usage is pretty much standard SQLAlchemy:

``` python
def create(request):
    data = request.json_body

    dse = model.DatabaseSchedulerEntry()
    dse.name = data.get('name')
    dse.task = data.get('task')
    dse.arguments = data.get('arguments')
    dse.keyword_arguments = data.get('kwarguments')
    dse.enabled = False
    dse.crontab = model.CrontabSchedule()
    request.dbsession.add(dse)
    request.dbsession.commit()
    return a_dictionary_representation_of_the_entry
```

I'm not familiar with Flask, so this might not work copy-pasted for you.

Also, I think you can still use beat entries as mentioned in Celery documentation: http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#beat-entries

**Comment by saadqc** [comment]
Thanks for the quick reply. I have tried your code and its working now.

**Comment by tuomur** [comment]
Updated project readme with the code example

**Comment by saadqc** [comment]
Thanks. I will add some more examples soon with Celery

**Comment by cescoferraro** [comment]
@tuomur have you considered making a flask extension out of this? [ I have been willing ](http://stackoverflow.com/q/30969814/3074508) to make this kind of schedule work with Flask for a long time with no success.  Have not tried your solution but it seems like it's perfectly coded. Would you mind it I fork it and give it a try as an extension? It would be cool if you could answer my question, hence it seems its the only beat/scheduler related question on SO. Thanks for the early Xmas gift

**Comment by tuomur** [comment]
I don't use Flask for anything so... no plans for extensions (although it seems to work for saadqc above just fine). You're welcome to fork it. PRs also accepted.

**Comment by saadqc** [comment]
@cescoferraro : yes i have tried with flask and made it work. let me add that

**Comment by saadqc** [comment]
@tuomur : i created an example project...the documentation is yet to be made. and i tried to push the code but seems like i dont have access. Could your please provide privileges?

**Comment by cescoferraro** [comment]
@saadqc can you push it to a bitbucket or anywhere else in the meanwhile?

**Comment by saadqc** [comment]
please check the quick tutorial i added in an hour...not very explanatory but hope it helps
https://github.com/saadqc/celery_sqlalchemy_scheduler/tree/patch-2

**Comment by cescoferraro** [comment]
@saadqc great man! But I think you did not added the examples files to your git repo before commiting.

**Comment by saadqc** [comment]
yeah...i am adding

**Comment by saadqc** [comment]
for now please use this...having some git issue while pushing to patch-2

https://github.com/saadqc/celery_sqlalchemy_scheduler/tree/master

**Comment by cescoferraro** [comment]
@saadqc  I owe you one

**Comment by cescoferraro** [comment]
@saadqc only way I got it to work was by adding PoolListener like this

``` python
class MyListener(PoolListener):
    def connect(self, dbapi_con, con_record):
        # dbapi_con.execute('PRAGMA journal_mode=OFF')
        dbapi_con.execute('PRAGMA synchronous=NORMAL')
        dbapi_con.execute('PRAGMA journal_mode=WAL')


engine = sqlalchemy.create_engine(SQLALCHEMY_DATABASE_URI, echo=False
                                  , listeners=[MyListener()]
                                  )
```

Otherwise I get I/O error even with the latest Sqlite. Have not you expirienced that? Got it to work with redis and rabbitmq as the broker but could not use Postgres as the Database which it what I was hoping to do. Gonna keep digging
