### ISSUE TITLE
How to dynamically add/remove tasks in runtime?

### ISSUE THREAD

**Issue by FX-HAO** [tuomur/celery_sqlalchemy_scheduler#3]
It works fine as like djceley's DatabaseScheule did. But the only problem is that it doesn't seem to send tasks that were added in runtime, then i restart the celery-beat, the tasks that were added before will be sent successfully.

So, is it possible to dynamically add/remove tasks without restarting celery-beat?

Thanks.

**Comment by tuomur** [comment]
It is possible, but the sync interval between beat's internal state and the database is several minutes by default. This of course means the task you added will not be picked up instantly. You can change the `DatabaseScheduler.sync_every` value to a faster one.
